apiVersion: apps/v1
kind: Deployment
metadata:
  name: dirtbike-gifs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dirtbike-gifs
  template:
    metadata:
      labels:
        app: dirtbike-gifs
    spec:
      containers:
      - name: dirtbike-gifs
        image: username/dirtbike-gifs:v1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: dirtbike-service
spec:
  selector:
    app: dirtbike-gifs
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
