name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Debug – Print directory and list files
        run: ls -R

      - name: Install dependencies
        run: |
          pip install -r ./app/requirements.txt

      - name: Run unit tests
        run: |
          pytest ./app/tests/test_main.py

      - name: Build Docker Image
        run: |
          docker build -t danmonti/flask-app:latest .

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "danmonti" --password-stdin

      - name: Push Docker Image
        run: |
          docker push danmonti/flask-app:latest

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
